name: flame_game
description: leaning how flame engine works, this game is public.
version: 0.1.0
publish_to: none

environment:
  sdk: ^2.17.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.7.0



flutter:
  assets: 

    - assets/images/



    # - assets\images\Sky.png
    # - assets\Characters\Duck\Duck.png
    # # - assets/Characters/Duck Girl/
    # - assets\Effects\Heart.png
    # - assets\Hazards\Spikes.png
    # - assets\Props\Door.png
    # - assets\Tiles\Tiles.png
    # # - assets\UI